# Generated by Django 5.2 on 2025-10-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaKosong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50, unique=True)),
                ('nama_barang', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('jumlah_barang', models.PositiveIntegerField(default=0)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar_barang/')),
            ],
            options={
                'verbose_name': 'Nota Kosong',
                'verbose_name_plural': 'Daftar Nota Kosong',
            },
        ),
    ]
