# Generated by Django 5.2 on 2025-10-15 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_sisa_bayar', models.DateField()),
                ('metode_pembayaran', models.CharField(choices=[('tunai', 'Tunai'), ('debit', 'Debit')], max_length=10)),
                ('total_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sisa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota Payment',
                'verbose_name_plural': 'Nota Payments',
            },
        ),
        migrations.AddField(
            model_name='notakosong',
            name='nota_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nota.notapayment'),
        ),
        migrations.AlterField(
            model_name='notakosong',
            name='kode_barang',
            field=models.CharField(max_length=50),
        ),
    ]
