# Generated by Django 5.2 on 2025-10-15 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0003_customer_transaksi_amount_paid_transaksi_change_and_more'),
        ('nota', '0002_auto_20251015_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapayment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kasir.customer'),
        ),
    ]
