# Generated by Django 5.2 on 2025-10-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0005_informasitoko'),
        ('nota', '0003_auto_20251015_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notakosong',
            name='nota_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nota.notapayment'),
        ),
        migrations.AlterField(
            model_name='notapayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.customer'),
        ),
    ]
