# Generated by Django 5.2 on 2025-10-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0004_alter_notakosong_nota_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapayment',
            name='is_temporary',
            field=models.BooleanField(default=True),
        ),
    ]
