# Generated by Django 5.2 on 2025-10-18 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0007_rename_alamat_customer_suplayer_alamat_suplayer_and_more'),
        ('nota', '0005_notapayment_is_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notapayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kasir.customer'),
        ),
    ]
