# Generated by Django 5.2 on 2025-10-18 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('kasir', 'Kasir'), ('admin', 'Admin')], max_length=10)),
                ('slogan', models.TextField(blank=True)),
                ('alamat', models.CharField(max_length=255)),
                ('no_telephon', models.CharField(max_length=20)),
                ('foto_profile', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
