# Generated by Django 5.2.7 on 2025-10-17 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kasir', '0007_rename_alamat_customer_suplayer_alamat_suplayer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_sisa_bayar', models.DateField()),
                ('metode_pembayaran', models.CharField(choices=[('tunai', 'Tunai'), ('debit', 'Debit')], max_length=10)),
                ('total_bayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sisa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suplayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.suplayer')),
            ],
            options={
                'verbose_name': 'Nota Payment',
                'verbose_name_plural': 'Nota Payments',
            },
        ),
        migrations.CreateModel(
            name='NotaSuplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50)),
                ('nama_barang', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('jumlah_barang', models.PositiveIntegerField(default=0)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar_barang/')),
                ('nota_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nota_suplayer.notapayment')),
            ],
            options={
                'verbose_name': 'Nota Suplayer',
                'verbose_name_plural': 'Daftar Nota Suplayer',
            },
        ),
    ]
