# Generated by Django 5.2 on 2025-10-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota_suplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapayment',
            name='is_temporary',
            field=models.BooleanField(default=True),
        ),
    ]
