# Generated by Django 5.2.7 on 2025-10-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('harga_barang', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.PositiveIntegerField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar_produk/')),
            ],
        ),
    ]
