# Generated by Django 5.2 on 2025-10-14 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.CharField(max_length=20, unique=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.produk')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.transaksi')),
            ],
        ),
    ]
