# Generated by Django 5.2 on 2025-10-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0003_customer_transaksi_amount_paid_transaksi_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alamat_customer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_telpon_customer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_agent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
