# Generated by Django 5.2 on 2025-10-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0004_customer_alamat_customer_customer_no_telpon_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformasiToko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('factory', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Informasi Toko',
                'verbose_name_plural': 'Informasi Toko',
            },
        ),
    ]
