# Generated by Django 5.2.7 on 2025-10-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0005_informasitoko'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat_customer', models.TextField(blank=True, null=True)),
                ('no_telpon_customer', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_agent', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
