# Generated by Django 5.2.7 on 2025-10-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0006_suplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suplayer',
            old_name='alamat_customer',
            new_name='alamat_suplayer',
        ),
        migrations.RenameField(
            model_name='suplayer',
            old_name='no_telpon_customer',
            new_name='no_telpon_suplayer',
        ),
    ]
